---generowanie sztywnego miesiaca
CREATE OR REPLACE TABLE `ceeregion-prod.Zestawienie_Miesieczne_2020.Styczen_2020` AS 
SELECT *
FROM `ceeregion-prod.Dashboardy.Dashboard_PL_Sales_2020`
WHERE _1_Data between 20200201 and 20200229;

----dowiazanie daty  z dim calendaer
CREATE OR REPLACE TABLE `ceeregion-prod.Zestawienie_Miesieczne_2020.Luty_2020` AS 
SELECT
_1_Data, 
b.date as Data, 
_2_Profit_Center as Profit_Center, 
_3_Customer_Groups as Customer_Groups, 
_4_Sales_District as Sales_District, 
Name_Sales_District, 
_5_Customer_information as Customer_information, 
_6_Order_No as Order_No, 
_7_Customer_No as Customer_No, 
_8_Insert_DE as Insert_DE, 
_9_Group_Insert_1 as Group_Insert_1, 
_10_Group_Insert_2 as Group_Insert_2, 
_11_Grupa_Insert_3 as Grupa_Insert_3, 
_12_PO_Type as PO_Type, 
_13_Quarter_of_year as Quarter_of_year, 
_14_Month as Month, 
_15_Day as Day, 
_16_Article_ID as Article_ID, 
_17_Conrad_External as Conrad_External,
_18_ABSMG_Sales_Quantity as ABSMG_Sales_Quantity, 
_19_Invoice_no as Invoice_no, 
_20_Article_No as Article_No, 
_21_Order_Pos as Order_Pos, 
_22_Brand as Brand, 
_23_MATKL as MATKL, 
_24_Document_type as Document_type, 
_25_Document_Name as Document_Name, 
_26_PaymentMethod as PaymentMethod, 
_27_Article_Name as Article_Name, 
_28_Catalog_Price_Net_EUR0 as Catalog_Price_Net_EUR0,
(_28_Catalog_Price_Net_EUR0 * 4.29520) as Catalog_Price_Net2_PLN,
_29_Price_Reduction_EURO, 
(_29_Price_Reduction_EURO * 4.29520) as Price_Reduction_PLN,
_30_Staggered_discount as Staggered_discount,
(_30_Staggered_discount * 4.29520) as Staggered_discount_PLN,
_31_Customer_Discount_EURO as Customer_Discount_EURO,
(_31_Customer_Discount_EURO * 4.29520) as Customer_Discount_PLN,
_32_Reduction as Reduction_EURO,
(_32_Reduction * 4.29520) as Reduction_PLN,
_33_Customer_full_Discount as Customer_full_Discount_EURO, 
(_33_Customer_full_Discount * 4.29520) as Customer_full_Discount_PLN, 
_34_Increments as Increments_EURO,
(_34_Increments * 4.29520) as Increments_PLN,
_35_NNT_EURO as  NNT_EURO,
(_35_NNT_EURO  * 4.29520) as NNT_PLN,
_36_COGS_EURO as COGS_EURO,
(_36_COGS_EURO * 4.29520) as COGS_PLN,  
_37_CM1_EURO as CM1_EURO,
(_37_CM1_EURO * 4.29520) as CM1_PLN,
_38_Catalog_revenues_EURO as Catalog_revenues_EURO,
(_38_Catalog_revenues_EURO * 4.29520) as Catalog_revenues_PLN,
_41_Calc_Discount_EURO as Calc_Discount_EURO, 
_42_User_Name as User_Name, 
_43_Customer_Name_1 as Customer_Name_1 , 
_44_Customer_Name_2 as Customer_Name_2 , 
_45_Customer_Name_3 as Customer_Name_3 , 
_46_Customer_Name_4 as Customer_Name_4 , 
_47_Head_Group as Head_Group , 
_48_Categorie as Categorie , 
_49_category_key as category_key , 
_50_Conditions as Conditions ,  
_51_Costs as Costs,
(_35_NNT_EURO * -0.01296) as Cost_Allocation

FROM `ceeregion-prod.Zestawienie_Miesieczne_2020.Styczen_2020` as a,
     `conrad-cbdp-prod-core.de_conrad_dwh1000_dwh_DimCalendar.DimCalendar` as b
     
WHERE a._1_Data = b.date_key;

--------dowiązanie walut
CREATE OR REPLACE TABLE `ceeregion-prod.Zestawienie_Miesieczne_2020.Styczen_2020` AS 
SELECT  
_1_Data,
Data, 
Profit_Center, 
Customer_Groups, 
Sales_District, 
Name_Sales_District, 
Customer_information, 
Order_No, 
Customer_No, 
Insert_DE, 
Group_Insert_1, 
Group_Insert_2, 
Grupa_Insert_3, 
PO_Type, 
Quarter_of_year, 
Month, 
Day, 
Article_ID, 
Conrad_External,
ABSMG_Sales_Quantity, 
Invoice_no, 
Article_No, 
Order_Pos, 
Brand, 
MATKL, 
Document_type, 
Document_Name, 
PaymentMethod, 
Article_Name, 
Catalog_Price_Net_EUR0,
(Catalog_Price_Net_EUR0 / b.rate) as Catalog_Price_Net2_PLN,
#(_28_Catalog_Price_Net_EUR0 * 4.29520) as Catalog_Price_Net_PLN,
_29_Price_Reduction_EURO as  Price_Reduction_EURO,
(_29_Price_Reduction_EURO / b.rate) as Price_Reduction_PLN,
#(_29_Price_Reduction_EURO * 4.29520) as Price_Reduction_PLN,
Staggered_discount as Staggered_discount_EURO,
(Staggered_discount / b.rate) as Staggered_discount_PLN,
#(_30_Staggered_discount * 4.29520) as Staggered_discount_PLN,
Customer_Discount_EURO,
(Customer_Discount_EURO / b.rate) as Customer_Discount_PLN,
#(_31_Customer_Discount_EURO * 4.29520) as Customer_Discount_PLN,
Reduction_EURO,
(Reduction_EURO / b.rate) as Reduction_PLN,
#(_32_Reduction * 4.29520) as Reduction_PLN,
Customer_full_Discount_EURO,
(Customer_full_Discount_EURO / b.rate) as Customer_full_Discount_PLN, 
#(_33_Customer_full_Discount * 4.29520) as Customer_full_Discount_PLN, 
Increments_EURO,
(Increments_EURO / b.rate) as Increments_PLN, 
#(_34_Increments * 4.29520) as Increments_PLN,
NNT_EURO,
(NNT_EURO / b.rate) as NNT_PLN,
#(_35_NNT_EURO  * 4.29520) as NNT_PLN,
COGS_EURO,
(COGS_EURO / b.rate) as COGS_PLN,
#(_36_COGS_EURO * 4.29520) as COGS_PLN,  
CM1_EURO,
(CM1_EURO / b.rate) as CM1_PLN,
#(_37_CM1_EURO * 4.29520) as CM1_PLN,
Catalog_revenues_EURO,
(Catalog_Price_Net_EUR0 / b.rate) as Catalog_Price_Net_PLN,
#(_38_Catalog_revenues_EURO * 4.29520) as Catalog_revenues_PLN,
Calc_Discount_EURO, 
User_Name, 
Customer_Name_1 , 
Customer_Name_2 , 
Customer_Name_3 , 
Customer_Name_4 , 
Head_Group, 
Categorie, 
category_key, 
Conditions,  
Costs,
Cost_Allocation,
#b.rate
FROM `ceeregion-prod.Zestawienie_Miesieczne_2020.Styczen_2020` as a,
    `conrad-cbdp-prod-core.de_conrad_dwh1000_dwh_FactExchangeRate.FactExchangeRate` as b
WHERE b.curr_key = "PLN"
and b.version_key = "ISJA20060201"
and _1_Data = b.date_key